# Generated by Django 2.1.4 on 2019-02-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('average_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('num_of_rates', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('in_process', 'В процессе'), ('completed', 'Закрыто')], default='pending', max_length=200)),
                ('photo_description_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_description_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_result_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_result_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('num_of_comments', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('rated_forms_id', models.ManyToManyField(blank=True, related_name='rated_forms_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
