# Generated by Django 2.1.4 on 2018-12-26 15:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('average_rate', models.FloatField(blank=True, default=0)),
                ('num_of_rates', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_process', 'In_Process'), ('completed', 'Completed')], default=('in_process', 'In_Process'), max_length=200)),
                ('photo_1', models.ImageField(upload_to='photo/%Y%m%d/')),
                ('photo_2', models.ImageField(upload_to='photo/%Y%m%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('closed_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
