# Generated by Django 2.1.4 on 2018-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(upload_to='photos/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(upload_to='photos/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_process', 'In_Process'), ('completed', 'Completed')], default=('pending', 'Pending'), max_length=200),
        ),
    ]
