# Generated by Django 2.1.4 on 2019-01-01 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0009_auto_20190101_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rated_forms_id',
            field=models.ManyToManyField(blank=True, related_name='rated_forms_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
