# Generated by Django 2.1.4 on 2019-01-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_rated_forms_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='num_of_comments',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
